on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: docker compose up -d
      - name: Set up credentials
        run: |
          echo AWS_REGION=ap-northeast-1 >> $GITHUB_ENV
          echo AWS_ACCESS_KEY_ID=dummy >> $GITHUB_ENV
          echo AWS_SECRET_ACCESS_KEY=dummy >> $GITHUB_ENV
      - run: curl http://localhost:8888
      - run: aws --endpoint-url=http://localhost:8888 dynamodb list-tables
        timeout-minutes: 1
      - run: aws --endpoint-url=http://localhost:8888 dynamodb describe-table --table-name test
        timeout-minutes: 1
